---
sidebar: sidebar 
permalink: custom-architectures-inventory-configure-block-nodes.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 'Spécifiez la configuration pour les nœuds de bloc individuels à l"aide de variables hôte (Host_var).' 
---
= Configurez des nœuds de bloc individuels
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Spécifiez la configuration pour les nœuds de bloc individuels à l'aide de variables hôte (Host_var).



== Présentation

Cette section décrit le remplissage d'un `host_vars/<BLOCK_NODE_HOSTNAME>.yml` fichier pour chaque nœud de bloc du cluster. Ces fichiers ne doivent contenir qu'une configuration unique à un nœud de bloc particulier. Les points suivants sont généralement utilisés :

* Nom du système (tel qu'il s'affiche dans System Manager).
* L'URL HTTPS pour l'un des contrôleurs (utilisée pour gérer le système à l'aide de son API REST).
* Quels nœuds de fichiers de protocole de stockage utilisent pour se connecter à ce nœud en mode bloc ?
* Configuration des ports HIC (carte d'interface hôte), tels que les adresses IP (si nécessaire).




== Étapes

Référencement du schéma d'adressage IP défini dans le link:custom-architectures-plan-file-system.html["Planifiez le système de fichiers"^] pour chaque noeud de bloc du cluster, créez un fichier `host_vars/<BLOCK_NODE_HOSTNAME>/yml` et remplir comme suit :

. En haut de la page, spécifier le nom du système et l'URL HTTPS pour l'un des contrôleurs :
+
[source, yaml]
----
eseries_system_name: <SYSTEM_NAME>
eseries_system_api_url: https://<MANAGEMENT_HOSTNAME_OR_IP>:8443/devmgr/v2/
----
. Sélectionner link:https://github.com/netappeseries/santricity/tree/release-1.3.1/roles/nar_santricity_host#role-variables["protocole"^] les nœuds de fichiers seront utilisés pour se connecter à ce nœud de bloc :
+
.. Protocoles pris en charge : `auto`, `iscsi`, `fc`, `sas`, `ib_srp`, `ib_iser`, `nvme_ib`, `nvme_fc`, `nvme_roce`.
+
[source, yaml]
----
eseries_initiator_protocol: <PROTOCOL>
----


. Selon le protocole utilisé, les ports HIC peuvent nécessiter des configurations supplémentaires. Si nécessaire, la configuration du port HIC doit être définie de sorte que l'entrée supérieure de la configuration de chaque contrôleur corresponde au port physique le plus à gauche de chaque contrôleur et au port inférieur le plus à droite. Tous les ports nécessitent une configuration valide même s'ils ne sont pas actuellement utilisés.
+

IMPORTANT: Reportez-vous également à la section ci-dessous si vous utilisez des nœuds de bloc EF600 (InfiniBand 200 Go) ou RoCE 200 Go avec les nœuds de bloc EF600.

+
.. Pour iSCSI :
+
[source, yaml]
----
eseries_controller_iscsi_port:
  controller_a:         # Ordered list of controller A channel definition.
    - state:            # Whether the port should be enabled. Choices: enabled, disabled
      config_method:    # Port configuration method Choices: static, dhcp
      address:          # Port IPv4 address
      gateway:          # Port IPv4 gateway
      subnet_mask:      # Port IPv4 subnet_mask
      mtu:              # Port IPv4 mtu
    - (...)             # Additional ports as needed.
  controller_b:         # Ordered list of controller B channel definition.
    - (...)             # Same as controller A but for controller B

# Alternatively the following common port configuration can be defined for all ports and omitted above:
eseries_controller_iscsi_port_state: enabled         # Generally specifies whether a controller port definition should be applied Choices: enabled, disabled
eseries_controller_iscsi_port_config_method: dhcp    # General port configuration method definition for both controllers. Choices: static, dhcp
eseries_controller_iscsi_port_gateway:               # General port IPv4 gateway for both controllers.
eseries_controller_iscsi_port_subnet_mask:           # General port IPv4 subnet mask for both controllers.
eseries_controller_iscsi_port_mtu: 9000              # General port maximum transfer units (MTU) for both controllers. Any value greater than 1500 (bytes).

----
.. Pour iser :
+
[source, yaml]
----
eseries_controller_ib_iser_port:
  controller_a:    # Ordered list of controller A channel address definition.
    -              # Port IPv4 address for channel 1
    - (...)        # So on and so forth
  controller_b:    # Ordered list of controller B channel address definition.
----
.. Pour NVMe/IB :
+
[source, yaml]
----
eseries_controller_nvme_ib_port:
  controller_a:    # Ordered list of controller A channel address definition.
    -              # Port IPv4 address for channel 1
    - (...)        # So on and so forth
  controller_b:    # Ordered list of controller B channel address definition.
----
.. Pour NVMe/RoCE :
+
[source, yaml]
----
eseries_controller_nvme_roce_port:
  controller_a:         # Ordered list of controller A channel definition.
    - state:            # Whether the port should be enabled.
      config_method:    # Port configuration method Choices: static, dhcp
      address:          # Port IPv4 address
      subnet_mask:      # Port IPv4 subnet_mask
      gateway:          # Port IPv4 gateway
      mtu:              # Port IPv4 mtu
      speed:            # Port IPv4 speed
  controller_b:         # Ordered list of controller B channel definition.
    - (...)             # Same as controller A but for controller B

# Alternatively the following common port configuration can be defined for all ports and omitted above:
eseries_controller_nvme_roce_port_state: enabled         # Generally specifies whether a controller port definition should be applied Choices: enabled, disabled
eseries_controller_nvme_roce_port_config_method: dhcp    # General port configuration method definition for both controllers. Choices: static, dhcp
eseries_controller_nvme_roce_port_gateway:               # General port IPv4 gateway for both controllers.
eseries_controller_nvme_roce_port_subnet_mask:           # General port IPv4 subnet mask for both controllers.
eseries_controller_nvme_roce_port_mtu: 4200              # General port maximum transfer units (MTU). Any value greater than 1500 (bytes).
eseries_controller_nvme_roce_port_speed: auto            # General interface speed. Value must be a supported speed or auto for automatically negotiating the speed with the port.
----
.. Les protocoles FC et SAS ne nécessitent pas de configuration supplémentaire. SRP n'est pas recommandé correctement.




Pour plus d'options de configuration des ports HIC et des protocoles hôte, notamment pour configurer iSCSI CHAP, reportez-vous au link:https://github.com/netappeseries/santricity/tree/release-1.3.1/roles/nar_santricity_host#role-variables["documentation"^] Inclus avec la collection SANtricity. Remarque lors du déploiement de BeeGFS, la configuration du pool de stockage, du volume et d'autres aspects du provisionnement du stockage sont configurés ailleurs et ne doivent pas être définis dans ce fichier.

Cliquez sur link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/host_vars/ictad22a01.yml["ici"^] par exemple, un fichier d'inventaire complet représentant un nœud de bloc unique.



=== Avec l'utilisation de HDR (200 Go) InfiniBand ou RoCE 200 Gb avec les nœuds de bloc NetApp EF600 :

Pour utiliser l'InfiniBand HDR (200 Go) avec la baie EF600, une seconde IP « virtuelle » doit être configurée pour chaque port physique. Voici un exemple de la bonne façon de configurer une baie EF600 équipée d'une carte InfiniBand HDR HIC double port :

[source, yaml]
----
eseries_controller_nvme_ib_port:
  controller_a:
    - 192.168.1.101 # Port 2a (physical)
    - 192.168.2.101 # Port 2a (virtual)
    - 192.168.1.100 # Port 2b (physical)
    - 192.168.2.100 # Port 2b (virtual)
  controller_b:
    - 192.168.3.101 # Port 2a (physical)
    - 192.168.4.101 # Port 2a (virtual)
    - 192.168.3.100 # Port 2b (physical)
    - 192.168.4.100 # Port 2b (virtual)
----