---
settings:
  name: BeeGFS on NetApp with E-Series Storage
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: fr-fr,us-en,ja-jp,zh-cn,zh-tw,ko-kr,de-de
sidebar:
  entries:
  - title: BeeGFS sur les documents NetApp
    url: "/index.html"
  - title: Commencez
    entries:
    - title: Ce qui est inclus dans ce site
      url: "/whats-included.html"
    - title: Termes et concepts
      url: "/beegfs-terms.html"
    - title: Générations de conception
      url: "/beegfs-gens.html"
    - title: Présentation de la solution
      url: "/beegfs-solution-overview.html"
    - title: Présentation de l'architecture
      url: "/beegfs-architecture-overview.html"
    - title: Exigences techniques
      url: "/beegfs-technology-requirements.html"
  - title: Examen du design de la solution
    entries:
    - title: Présentation du design
      url: "/beegfs-design-overview.html"
    - title: Configuration matérielle
      url: "/beegfs-design-hardware-architecture.html"
    - title: Configuration logicielle
      url: "/beegfs-design-software-architecture.html"
    - title: Vérification de la conception
      url: "/beegfs-design-solution-verification.html"
    - title: Instructions de dimensionnement
      url: "/beegfs-design-solution-sizing-guidelines.html"
    - title: Réglage des performances
      url: "/beegfs-design-performance-tuning.html"
  - title: Déploiement de la solution
    entries:
    - title: Présentation du déploiement
      url: "/beegfs-deploy-overview.html"
    - title: Découvrez l'inventaire Ansible
      url: "/beegfs-deploy-learn-ansible.html"
    - title: Passez en revue les bonnes pratiques
      url: "/beegfs-deploy-bestpractice.html"
    - title: Déployez le matériel
      url: "/beegfs-deploy-hardware.html"
    - title: Déployez des logiciels
      entries:
      - title: Configurez les nœuds de fichiers et de blocs
        url: "/beegfs-deploy-setup-nodes.html"
      - title: Réglez les paramètres du système en fonction des performances
        url: beegfs-deploy-file-node-tuning.html
      - title: Configurez le nœud de contrôle Ansible
        url: "/beegfs-deploy-setting-up-an-ansible-control-node.html"
      - title: Créer un inventaire Ansible
        url: "/beegfs-deploy-create-inventory.html"
      - title: Définir des éléments de base BeeGFS
        url: "/beegfs-deploy-define-inventory.html"
      - title: Déployez BeeGFS
        url: "/beegfs-deploy-playbook.html"
      - title: Configurer les clients BeeGFS
        url: "/beegfs-deploy-configure-clients.html"
    - title: Faire évoluer les clusters BeeGFS
      url: "/beegfs-deploy-scale-building-blocks.html"
    - title: Pourcentages de volume recommandés
      url: "/beegfs-deploy-recommended-volume-percentages.html"
  - title: Mentions légales
    url: "/legal-notices.html"
product-family:
  name: E-Series
  repo: e-series-family
