---
sidebar: sidebar 
permalink: second-gen/beegfs-solution-overview.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: 'La solution BeeGFS sur NetApp associe le système de fichiers parallèle BeeGFS aux systèmes de stockage NetApp EF600 à une infrastructure fiable, évolutive et économique qui s"adapte aux besoins des workloads les plus exigeants.' 
---
= Présentation de la solution
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La solution BeeGFS sur NetApp associe le système de fichiers parallèle BeeGFS aux systèmes de stockage NetApp EF600 à une infrastructure fiable, évolutive et économique qui s'adapte aux besoins des workloads les plus exigeants.



== Programme NVA

La solution BeeGFS sur NetApp fait partie du programme NVA (NetApp Verified Architecture), qui fournit aux clients des configurations de référence et des conseils de dimensionnement pour des workloads et des cas d'utilisation spécifiques. Les solutions NVA sont minutieusement testées et conçues pour réduire les risques de déploiement et accélérer le délai de mise sur le marché.



== Présentation de la conception

La solution BeeGFS sur NetApp est une architecture modulaire qui peut être configurée pour de nombreux workloads exigeants. Que ce soit pour gérer de nombreux fichiers de petite taille, des opérations de fichiers volumineux ou une charge de travail hybride, le système de fichiers peut être personnalisé pour répondre à ces besoins. Grâce à une structure matérielle à deux niveaux, la haute disponibilité est intégrée. Elle permet un basculement indépendant sur plusieurs couches matérielles et garantit des performances prévisibles, même en cas de dégradation partielle du système. Le système de fichiers BeeGFS permet de créer un environnement haute performance et évolutif sur différentes distributions Linux. Il offre aux clients un seul namespace de stockage facilement accessible. Pour en savoir plus, consultez le link:beegfs-architecture-overview.html["présentation de l'architecture"].



== Cas d'utilisation

Les utilisations suivantes s'appliquent à la solution BeeGFS sur NetApp :

* Systèmes NVIDIA DGX SuperPOD équipés de DGX avec DGX A100, H100, H200 et B200 GPU.
* L'intelligence artificielle (IA), comprenant le machine learning (ML), le deep learning (DL), le traitement du langage naturel à grande échelle (NLP) et la compréhension du langage naturel (NLU). Pour plus d'informations, voir https://www.netapp.com/blog/beefs-for-ai-fact-vs-fiction/["BeeGFS pour l'IA : faits plutôt que fiction"^].
* Informatique hautes performances (HPC), y compris les applications accélérées par MPI (interface de transmission de messages) et d'autres techniques informatiques distribuées. Pour plus d'informations, voir https://www.netapp.com/blog/beegfs-for-ai-ml-dl/["Pourquoi BeeGFS va bien au-delà de l'HPC"^].
* Charges de travail applicatives caractérisées par :
+
** Lecture ou écriture dans des fichiers supérieurs à 1 Go
** Lecture ou écriture dans le même fichier par plusieurs clients (dizaines, centaines et milliers)


* Jeux de données de plusieurs téraoctets ou de plusieurs pétaoctets.
* Environnements qui nécessitent un seul espace de noms de stockage optimal pour un mélange de fichiers de petite ou de grande taille.




== Avantages

Voici les principaux avantages de BeeGFS sur NetApp :

* La disponibilité de conceptions matérielles vérifiées permet l'intégration complète des composants matériels et logiciels pour assurer des performances prévisibles et une fiabilité optimale.
* Déploiement et gestion avec Ansible pour une simplicité et une cohérence à grande échelle.
* Contrôle et observabilité fournis avec l'analyseur de performance E-Series et le plug-in BeeGFS. Pour plus d'informations, voir https://www.netapp.com/blog/monitoring-netapp-eseries/["Présentation d'un cadre de surveillance des solutions NetApp E-Series"^].
* Haute disponibilité dotée d'une architecture de disques partagés qui assure la durabilité et la disponibilité des données.
* Prise en charge des fonctionnalités modernes de gestion et d'orchestration des workloads à l'aide de conteneurs et de Kubernetes. Pour plus d'informations, voir https://www.netapp.com/blog/kubernetes-meet-beegfs/["Kubernetes et BeeGFS : un récit d'investissement pérenne"^].

