---
sidebar: sidebar 
permalink: beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Pour configurer un nœud de contrôle Ansible, identifiez une machine virtuelle ou physique avec un accès réseau aux ports de gestion de tous les nœuds de fichiers et de blocs qui peuvent être utilisés pour configurer la solution. 
---
= Configurez un nœud de contrôle Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour configurer un nœud de contrôle Ansible, vous devez identifier une machine virtuelle ou physique avec un accès réseau aux ports de gestion de tous les nœuds de fichiers et de blocs qui peuvent être utilisés pour configurer la solution.

Les étapes suivantes ont été testées sur CentOS 8.4. Pour connaître les étapes spécifiques à votre distribution Linux préférée, reportez-vous au https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Documentation Ansible"^].

. Installer Python 3.9 et s'assurer que la version correcte de `pip` est installé.
+
....
sudo dnf install python3.9 -y
sudo dnf install python39-pip
sudo dnf install sshpass
....
. Créez des liens symboliques, en vous assurant que le binaire Python 3.9 est utilisé chaque fois `python3` ou `python` est appelé.
+
....
sudo ln -sf /usr/bin/python3.9 /usr/bin/python3
sudo ln -sf /usr/bin/python3 /usr/bin/python
....
. Installez les packages Python requis par les collections NetApp BeeGFS.
+
....
python3 -m pip install ansible cryptography netaddr
....
+

NOTE: Pour vous assurer que vous installez une version prise en charge d'Ansible et de tous les packages Python requis, consultez le fichier Lisezmoi de la collection BeeGFS. Les versions prises en charge sont également présentées dans le link:beegfs-technology-requirements.html["Exigences techniques"].

. Vérifiez que les versions correctes d'Ansible et de Python sont installées.
+
....
ansible --version
ansible [core 2.11.6]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Mar 10 2021, 17:29:56) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.2
  libyaml = True
....
. Stockez les inventaires Ansible utilisés pour décrire le déploiement BeeGFS dans des systèmes de contrôle source tels que Git ou BitBucket, puis installez Git pour interagir avec ces systèmes.
+
....
sudo dnf install git -y
....
. Configurez SSH sans mot de passe. C'est le moyen le plus simple de permettre à Ansible d'accéder aux nœuds de fichiers BeeGFS distants à partir du nœud de contrôle Ansible.
+
.. Sur le nœud de contrôle Ansible, si nécessaire, générez une paire de clés publiques à l'aide de `ssh-keygen`
.. Configurez SSH sans mot de passe sur chacun des nœuds de fichiers à l'aide de `ssh-copy-id <ip_or_hostname>`
+
Do *NOT* configurez SSH sans mot de passe sur les nœuds de bloc. Cela n'est ni pris en charge ni obligatoire.



. Utilisez Ansible Galaxy pour installer la version de la collection BeeGFS répertoriée dans link:beegfs-technology-requirements.html["Exigences techniques"].
+
Cette installation inclut des dépendances Ansible supplémentaires, telles que le logiciel NetApp SANtricity et les collections d'hôtes.

+
....
ansible-galaxy collection install netapp_eseries.beegfs:==3.0.1
....

