---
sidebar: sidebar 
permalink: second-gen/beegfs-deploy-overview.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: 'Vous pouvez déployer BeeGFS sur NetApp pour des nœuds de fichiers et de blocs validés en utilisant la deuxième génération de l"architecture de base BeeGFS de NetApp.' 
---
= Présentation du déploiement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BeeGFS sur NetApp peut être déployé sur des nœuds de blocs et de fichiers validés à l'aide d'Ansible et de la conception d'éléments de base BeeGFS de NetApp.



== Collections et rôles Ansible

La solution BeeGFS sur NetApp est déployée à l'aide d'Ansible, un moteur d'automatisation IT couramment utilisé pour automatiser les déploiements d'applications. Ansible utilise une série de fichiers appelée collectivement l'inventaire, qui modélise le système de fichiers BeeGFS que vous souhaitez déployer.

Ansible permet à des entreprises comme NetApp de développer leur activité grâce aux fonctionnalités intégrées à l'aide de collections disponibles sur Ansible Galaxy (voir https://galaxy.ansible.com/netapp_eseries/santricity["Collection NetApp E-Series BeeGFS"^]). Elles comprennent des modules qui exécutent des fonctions ou des tâches spécifiques (telles que la création d'un volume E-Series) ainsi que des rôles pouvant appeler plusieurs modules ou d'autres rôles. Cette approche automatisée réduit la durée de déploiement du système de fichiers BeeGFS et du cluster HA sous-jacent. De plus, il simplifie la maintenance et l'extension du cluster et du système de fichiers BeeGFS.

Pour plus de détails, voir link:beegfs-deploy-learn-ansible.html["Découvrez l'inventaire Ansible"].


NOTE: Comme de nombreuses étapes sont nécessaires pour déployer la solution BeeGFS sur NetApp, NetApp ne prend pas en charge le déploiement manuel de la solution.



== Profils de configuration pour les éléments de base BeeGFS

Les procédures de déploiement couvrent les profils de configuration suivants :

* Un seul élément de base inclut des services de gestion, de métadonnées et de stockage.
* Un second élément de base qui inclut les métadonnées et les services de stockage.
* Un troisième élément inclut uniquement des services de stockage.


Ces profils illustrent la gamme complète de profils de configuration recommandés pour les éléments de base NetApp BeeGFS. Pour chaque déploiement, le nombre d'éléments de base de métadonnées et de stockage ou de services de stockage uniquement peut varier en fonction des exigences de capacité et de performances.



== Présentation des étapes de déploiement

Le déploiement implique plusieurs tâches générales :

.Déploiement matériel
. Assembler physiquement chaque élément de bâtiment.
. Installez le rack et le matériel de câblage. Pour des procédures détaillées, voir link:beegfs-deploy-hardware.html["Déployez le matériel"].


.De déploiement logiciel
. link:beegfs-deploy-setup-nodes.html["Configurez les nœuds de fichiers et de blocs"].
+
** Configurez les adresses IP BMC sur les nœuds de fichiers
** Installez un système d'exploitation pris en charge et configurez la mise en réseau de gestion sur les nœuds de fichiers
** Configurez les adresses IP de gestion sur les nœuds de bloc


. link:beegfs-deploy-setting-up-an-ansible-control-node.html["Configurez un nœud de contrôle Ansible"].
. link:beegfs-deploy-file-node-tuning.html["Réglez les paramètres du système en fonction des performances"].
. link:beegfs-deploy-create-inventory.html["Créez l'inventaire Ansible"].
. link:beegfs-deploy-define-inventory.html["Définissez l'inventaire Ansible pour les éléments de base BeeGFS"].
. link:beegfs-deploy-playbook.html["Déploiement de BeeGFS avec Ansible"].
. link:beegfs-deploy-configure-clients.html["Configurer les clients BeeGFS"].



NOTE: Les procédures de déploiement incluent plusieurs exemples où du texte doit être copié dans un fichier. Portez une attention particulière aux commentaires en ligne signalés par les caractères “#” ou “//” pour tout ce qui doit ou peut être modifié pour un déploiement spécifique. Par exemple :
`beegfs_ha_ntp_server_pools:  # THIS IS AN EXAMPLE OF A COMMENT!
  - "pool 0.pool.ntp.org iburst maxsources 3"
  - "pool 1.pool.ntp.org iburst maxsources 3"`

Architectures dérivées avec variations dans les recommandations de déploiement :

* link:beegfs-design-high-capacity-building-block.html["Élément de base haute capacité"]

