---
sidebar: sidebar 
permalink: second-gen/beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Pour configurer un nœud de contrôle Ansible, identifiez une machine virtuelle ou physique avec un accès réseau aux ports de gestion de tous les nœuds de fichiers et de blocs qui peuvent être utilisés pour configurer la solution. 
---
= Configurez un nœud de contrôle Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour configurer un nœud de contrôle Ansible, vous devez désigner une machine virtuelle ou physique qui accède au réseau à tous les nœuds de blocs et de fichiers déployés pour la solution BeeGFS sur NetApp.

Consultez le link:beegfs-technology-requirements.html#ansible-control-node-requirements["Exigences techniques"] pour obtenir la liste des versions de package recommandées. Les étapes suivantes ont été testées sur Ubuntu 22.04. Pour connaître les étapes spécifiques à votre distribution Linux préférée, consultez le https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Documentation Ansible"^].

. À partir de votre nœud de contrôle Ansible, installez les packages Python et Python Virtual Environment suivants.
+
[source, console]
----
sudo apt-get install python3 python3-pip python3-setuptools python3.10-venv
----
. Créez un environnement virtuel Python
+
[source, console]
----
python3 -m venv ~/pyenv
----
. Activer l'environnement virtuel.
+
[source, console]
----
source ~/pyenv/bin/activate
----
. Installez les packages Python requis dans l'environnement virtuel activé.
+
[source, console]
----
pip install ansible netaddr cryptography passlib
----
. Installez la collection BeeGFS à l'aide d'Ansible Galaxy.
+
[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs
----
. Vérifiez que les versions installées d'Ansible, Python et de la collection BeeGFS correspondent auxlink:beegfs-technology-requirements.html#ansible-control-node-requirements["Exigences techniques"]
+
[source, console]
----
ansible --version
ansible-galaxy collection list netapp_eseries.beegfs
----
. Configurez SSH sans mot de passe pour permettre à Ansible d'accéder aux nœuds de fichiers BeeGFS distants à partir du nœud de contrôle Ansible.
+
.. Le cas échéant, générez une paire de clés publiques sur le nœud de contrôle Ansible.
+
[source, console]
----
ssh-keygen
----
.. Configurez SSH sans mot de passe sur chacun des nœuds de fichiers.
+
[source, console]
----
ssh-copy-id <ip_or_hostname>
----





IMPORTANT: Do *NOT* configurez SSH sans mot de passe sur les nœuds de bloc. Cela n'est ni pris en charge ni obligatoire.
