---
sidebar: sidebar 
permalink: second-gen/beegfs-technology-requirements.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Pour implémenter la solution BeeGFS sur NetApp, assurez-vous que votre environnement répond aux exigences technologiques. 
---
= Exigences techniques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pour implémenter la solution BeeGFS sur NetApp, assurez-vous que votre environnement répond aux exigences technologiques indiquées dans ce document.



== Aperçu des exigences

Cette page détaille les exigences matérielles, logicielles et micrologicielles pour la mise en œuvre de BeeGFS sur NetApp éléments de base. Les exigences sont organisées dans les sections suivantes :

* <<Configuration matérielle requise>> - Nœuds de fichiers (matériel/logiciel/micrologiciel), nœuds de blocs (matériel/micrologiciel), réseau et câblage
* <<Configuration requise pour le déploiement de logiciels>> - Composants déployés par Ansible
* <<Configuration requise pour le nœud de contrôle Ansible>> - Versions logicielles du nœud de contrôle




== Configuration matérielle requise

Avant de commencer, assurez-vous que votre matériel respecte les spécifications suivantes pour un seul élément de base de la solution BeeGFS sur NetApp. Les composants exacts d'un déploiement particulier peuvent varier selon les exigences du client. Chaque nœud de fichiers doit respecter ou dépasser ces spécifications pour atteindre les performances attendues.



=== Configuration requise pour les nœuds de fichiers

[cols="10%,90%"]
|===
| Quantité | Caractéristiques 


| 2  a| 
*Lenovo ThinkSystem SR665 V3*

*Matériel :*

* *Processeurs :* 2x AMD EPYC 9124 16C 3.0 GHz (configurés en deux zones NUMA)
* *Mémoire :* 256 Go (16 x 16 Go TruDDR5 4800 MHz RDIMM-A)
* *Extension PCIe :* quatre emplacements PCIe Gen5 x16 (deux par zone NUMA)
* *Cartes HCA :* 4x MCX755106AS-HEAT ConnectX-7, NDR200, QSFP112, 2 ports, PCIe Gen5 x16, InfiniBand Adapter
* *Stockage :* Deux disques en RAID 1 pour le système d’exploitation (1TB 7.2K SATA ou mieux)
* *Gestion :* port 1 GbE pour la gestion du système d’exploitation en bande
* *BMC :* BMC 1GbE avec API Redfish pour la gestion hors bande du serveur
* *Alimentation :* Deux alimentations remplaçables à chaud et ventilateurs haute performance


*Logiciels et micrologiciels*

* *Système d'exploitation :* Red Hat 9.4 Server Physical avec haute disponibilité (2 socket)
* *Noyau Linux :* 5.14.0-427.42.1.el9_4.x86_64
* *Firmware HCA :* FW: 28.46.1006, PXE: 3.8.0100, UEFI: 14.39.0013


|===

IMPORTANT: Les nœuds de fichiers nécessitent un abonnement valide à Red Hat Enterprise Linux Server et au Red Hat Enterprise Linux High Availability Add-On.



=== Exigences relatives aux nœuds de bloc

Chaque élément de base nécessite deux matrices E-Series du même modèle. Ne mélangez pas les modèles de matrices au sein d'un même élément de base.

[cols="10%,20%,70%"]
|===
| Quantité | Modèle | Caractéristiques 


| 2 | EF80  a| 
*Matériel :*

* *Mémoire :* 128GB (64GB par controller)
* *Adaptateur :* 2x 2 ports 200 Gb/NDR (NVMe/IB)
* *Disques :* Configurés pour correspondre aux métadonnées souhaitées et à la capacité de stockage


*Micrologiciel :*

* *SANtricity OS :* 12.00
* *NVSRAM :* NEF80-200834-D00
* *Micrologiciel du disque :* Dernière version disponible pour vos modèles de disque (voir link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["Site du firmware du disque E-Series"^])




| 2 | EF600  a| 
*Matériel :*

* *Mémoire :* 256 Go (128 Go par contrôleur)
* *Adaptateur :* 2-port 200Gb/HDR (NVMe/IB)
* *Disques :* Configurés pour correspondre aux métadonnées souhaitées et à la capacité de stockage


*Micrologiciel :*

* *SANtricity OS :* 11.90R5
* *NVSRAM :* N6000-890834-D02
* *Micrologiciel du disque :* Dernière version disponible pour vos modèles de disque (voir link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["Site du firmware du disque E-Series"^])


|===


=== Exigences relatives aux commutateurs de réseau de stockage

[cols="10%,90%"]
|===
| Quantité | Caractéristiques 


| 1  a| 
*Commutateur NVIDIA QM9700 Quantum 2 NDR InfiniBand*

Le commutateur réseau de stockage doit supporter des vitesses de 200Gb/s InfiniBand. Le NVIDIA QM9700 est le commutateur recommandé pour le cluster.

|===

NOTE: D'autres commutateurs, tels que le NVIDIA MQM8700 Quantum, peuvent être utilisés mais nécessitent un câblage différent.



=== Exigences de câblage



==== Câbles du nœud bloc au nœud fichier

Les connexions directes entre les nœuds de blocs et les nœuds de fichiers nécessitent les câbles suivants :

[cols="15%,60%,25%"]
|===
| Quantité | Spécification du câble | Longueur 


| 8 | MCP1650-H001E30 - Câble cuivre passif NVIDIA, QSFP56, 200 Gb/s | 1 m 
|===


==== Câbles du nœud de fichiers au commutateur de stockage

Les types de câbles suivants sont recommandés pour le commutateur NVIDIA QM9700 Quantum 2. Choisissez entre fibre optique active et cuivre passif selon vos besoins. Les quantités sont indiquées par élément de base.

[cols="20%,15%,10%,55%"]
|===
| Changer de modèle | Type de câble | Quantité | Référence 


.4+| NVIDIA QM9700 .3+| Fibre active (émetteurs-récepteurs inclus) | 2 | MMA4Z00-NS (multimode, IB/ETH, 800 Go/s 2x400 Go/s double port OSFP) 


| 4 | MFP7E20-Nxxx (multimode, câble fibre de séparation 4 canaux à deux canaux) 


| 8 | MMA1Z00-NS400 (multimode, IB/ETH, 400 Go/s, QSFP-112 à port unique) 


| Cuivre passif | 2 | MCP7Y40-N002 (câble répartiteur en cuivre passif NVIDIA, InfiniBand 800 Go/s à 4 200 Go/s, OSFP à 4 x QSFP112) 
|===


=== Configuration requise pour le déploiement de logiciels

Le tableau suivant répertorie les exigences logicielles déployées automatiquement dans le cadre du déploiement BeeGFS basé sur Ansible.

[cols="20%,80%"]
|===
| Logiciel | Version 


| BeeGFS | 8.2.2 


| Corosync | 3.1.8-1 


| Stimulateur cardiaque | 2.1.7-5,2 


| Agents de clôture (sébaste/apc) | 4.10.0-62 


| Pilotes InfiniBand / RDMA | DOCA-OFED-25.04-0.6.1 
|===


=== Configuration requise pour le nœud de contrôle Ansible

La solution BeeGFS sur NetApp est déployée et gérée à partir d'un nœud de contrôle Ansible. Pour plus d'informations, reportez-vous à la section https://docs.ansible.com/ansible/latest/network/getting_started/basic_concepts.html["Documentation Ansible"^].

Les exigences logicielles répertoriées dans les tableaux suivants sont spécifiques à la version de la collection NetApp BeeGFS Ansible indiquée ci-dessous.

[cols="30%,70%"]
|===
| Logiciel | Version 


| Cœur Ansible | >= 2.19.0 


| Python | 3,12 


| Packs Python supplémentaires | Cryptography-46.0.3, netaddr-1.3.0, ipaddr-2.2.0 


| Collection Ansible NetApp E-Series BeeGFS | 4.0.0 
|===