---
sidebar: sidebar 
permalink: beegfs-design-overview.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Pour prendre en charge la solution BeeGFS sur NetApp, qui associe le système de fichiers parallèle BeeGFS et les systèmes de stockage NetApp EF600, vous devez utiliser un équipement, un câblage et des configurations spécifiques. 
---
= Présentation du design
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Pour prendre en charge la solution BeeGFS sur NetApp, qui associe le système de fichiers parallèle BeeGFS et les systèmes de stockage NetApp EF600, vous devez utiliser un équipement, un câblage et des configurations spécifiques.

En savoir plus :

* link:beegfs-design-hardware-architecture.html["Configuration matérielle"]
* link:beegfs-design-software-architecture.html["Configuration logicielle"]
* link:beegfs-design-solution-verification.html["Vérification de la conception"]
* link:beegfs-design-solution-sizing-guidelines.html["Instructions de dimensionnement"]
* link:beegfs-design-performance-tuning.html["Réglage des performances"]


Architectures dérivées avec des variations de conception et de performances :

* link:beegfs-design-high-capacity-building-block.html["Élément de base haute capacité"]

