---
sidebar: sidebar 
permalink: deploy-features-integration/beegfs-csi-driver/csi-driver-prereqs.html 
keywords: BeeGFS Features, CSI, Driver 
summary: Prérequis pour le déploiement du pilote CSI BeeGFS 
---
= Prérequis pour le déploiement du pilote CSI BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Avant de déployer et de configurer le pilote CSI BeeGFS, assurez-vous de disposer d'un cluster Kubernetes en cours d'exécution, d'un accès à votre cluster BeeGFS et des autorisations appropriées pour installer les ressources à l'échelle du cluster.



== Vérifier la configuration de Kubernetes

Exécutez la commande suivante pour vérifier l'état des pods dans votre cluster Kubernetes :

[source, console]
----
kubectl get pods
----
**Résultat attendu :**

[listing]
----
root@node01:/etc/cni/net.d# kubectl get pods
No resources found in default namespace.
----
Si aucun pod n'est en cours d'exécution, la liste sera vide.  Sinon, les pods devraient être listés sans erreur.



== Valider le client et les services BeeGFS

Vérifiez que le cluster BeeGFS est sain et que tous les services sont accessibles en exécutant la commande suivante :

**BeeGFS 7.4**

[source, console]
----
beegfs-check-servers
----
**BeeGFS 8**

[source, console]
----
beegfs health check
----

NOTE: Le pilote CSI fonctionne avec les deux `beegfs-dkms-client` et `beegfs-client` , qui doit être installé sur chaque nœud Kubernetes.  Pour connaître les étapes d'installation, consultez la documentation DKMS du client BeeGFS : https://doc.beegfs.io/latest/advanced_topics/client_dkms.html[]

**Résultat attendu de BeeGFS 7.4 :**

[listing]
----
root@node01:/home/user_id/beegfs-csi-driver# beegfs-check-servers
Management
==========
mgmt [ID: 1]: reachable at XXX.X.AB.1:8008 (protocol: TCP)

Metadata
==========
meta_25_tgt_2501 [ID: 2501]: reachable at XXX.X.AA.MN:8255 (protocol: RDMA)
meta_26_tgt_2601 [ID: 2601]: reachable at XXX.X.BB.NO:8265 (protocol: RDMA)
meta_27_tgt_2701 [ID: 2701]: reachable at XXX.X.AA.OP:8275 (protocol: RDMA)
meta_28_tgt_2801 [ID: 2801]: reachable at XXX.X.BB.PQ:8285 (protocol: RDMA)
meta_29_tgt_2901 [ID: 2901]: reachable at XXX.X.AA.QR:8295 (protocol: RDMA)
meta_30_tgt_3001 [ID: 3001]: reachable at XXX.X.BB.RS:8305 (protocol: RDMA)
meta_31_tgt_3101 [ID: 3101]: reachable at XXX.X.AA.ST:8315 (protocol: RDMA)
meta_32_tgt_3201 [ID: 3201]: reachable at XXX.X.BB.TU:8325 (protocol: RDMA)

Storage
==========
stor_25_tgt_2501 [ID: 2501]: reachable at XXX.X.CC.MN:8253 (protocol: RDMA)
stor_26_tgt_2601 [ID: 2601]: reachable at XXX.X.DD.NO:8263 (protocol: RDMA)
stor_27_tgt_2701 [ID: 2701]: reachable at XXX.X.CC.OP:8273 (protocol: RDMA)
stor_28_tgt_2801 [ID: 2801]: reachable at XXX.X.DD.PQ:8283 (protocol: RDMA)
stor_29_tgt_2901 [ID: 2901]: reachable at XXX.X.CC.QR:8293 (protocol: RDMA)
stor_30_tgt_3001 [ID: 3001]: reachable at XXX.X.DD.RS:8303 (protocol: RDMA)
stor_31_tgt_3101 [ID: 3101]: reachable at XXX.X.CC.ST:8313 (protocol: RDMA)
stor_32_tgt_3201 [ID: 3201]: reachable at XXX.X.DD.32:8323 (protocol: RDMA)
----
Si certains services sont inaccessibles, assurez-vous que le client BeeGFS est correctement configuré et que la connectivité réseau aux serveurs BeeGFS est fonctionnelle.
