---
sidebar: sidebar 
permalink: administer-clusters-failover-failback.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, failover, failback, recovery 
summary: Déplacement des services BeeGFS entre les nœuds du cluster. 
---
= Services de basculement/rétablissement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Déplacement des services BeeGFS entre les nœuds du cluster.



== Présentation

Les services BeeGFS peuvent basculer entre les nœuds du cluster pour s'assurer que les clients sont en mesure de continuer à accéder au système de fichiers en cas de défaillance d'un nœud ou si vous devez effectuer une maintenance planifiée. Cette section décrit différentes méthodes permettant aux administrateurs d'effectuer une réparation sur le cluster après une reprise d'activité ou de déplacer manuellement les services entre les nœuds.



== Étapes



=== Basculement et rétablissement



==== Basculement (planifié)

De manière générale, lorsque vous devez mettre un nœud de fichier unique hors ligne pour les opérations de maintenance, vous devez déplacer (ou vidanger) tous les services BeeGFS depuis ce nœud. Pour ce faire, le nœud peut d'abord être en veille :

`pcs node standby <HOSTNAME>`

Après vérification de l'utilisation `pcs status` toutes les ressources ont été redémarrées sur le nœud de fichier secondaire, vous pouvez arrêter ou apporter d'autres modifications au nœud si nécessaire.



==== Restauration (après un basculement planifié)

Lorsque vous êtes prêt à restaurer les services BeeGFS sur le nœud préféré s'exécutent d'abord `pcs status` Et vérifiez dans la « liste de nœuds » que l'état est en veille. Si le nœud a été redémarré, il s'affiche hors ligne jusqu'à ce que vous mettent les services du cluster en ligne :

[source, console]
----
pcs cluster start <HOSTNAME>
----
Une fois le nœud mis en ligne hors veille, grâce à :

[source, console]
----
pcs cluster node unstandby <HOSTNAME>
----
Enfin, transférez tous les services BeeGFS vers leurs nœuds préférés avec :

[source, console]
----
pcs resource relocate run
----


==== Retour arrière (après basculement non planifié)

Si un nœud présente un défaut matériel ou autre, le cluster haute disponibilité doit réagir automatiquement et déplacer ses services vers un nœud sain, ce qui permet aux administrateurs de prendre des mesures correctives. Avant de continuer, reportez-vous à la link:administer-clusters-troubleshoot.html["dépannage"^] section pour déterminer la cause du basculement et résoudre tout problème en suspens. Une fois le nœud mis sous tension et en bon état, vous pouvez continuer à le restaurer.

Lorsqu'un nœud démarre après un redémarrage non planifié (ou planifié), les services de cluster ne sont pas configurés pour démarrer automatiquement. Vous devez donc mettre le nœud en ligne avec :

[source, console]
----
pcs cluster start <HOSTNAME>
----
Ensuite, nettoyez toute défaillance de ressource et réinitialisez l'historique d'escrime du nœud :

[source, console]
----
pcs resource cleanup node=<HOSTNAME>
pcs stonith history cleanup <HOSTNAME>
----
Vérifier dans `pcs status` le nœud est en ligne et fonctionne correctement. Par défaut, les services BeeGFS ne sont pas automatiquement rebasculer afin d'éviter tout déplacement accidentel des ressources vers un nœud malsain. Une fois que vous êtes prêt à renvoyer toutes les ressources du cluster à leurs nœuds préférés avec :

[source, console]
----
pcs resource relocate run
----


=== Déplacement de services BeeGFS individuels vers d'autres nœuds de fichiers



==== Déplacer définitivement un service BeeGFS vers un nouveau noeud de fichier

Si vous souhaitez modifier de manière permanente le nœud de fichier favori pour un service BeeGFS, ajustez l'inventaire Ansible de sorte que le nœud préféré soit répertorié en premier et exécutez à nouveau le PlayBook Ansible.

Par exemple dans cet exemple `inventory.yml` File, ictad22h01 est le nœud de fichier préféré pour exécuter le service de gestion BeeGFS :

[source, yaml]
----
        mgmt:
          hosts:
            ictad22h01:
            ictad22h02:
----
Inverser l'ordre ferait que les services de gestion seraient préférés sur ictad22h02:

[source, yaml]
----
        mgmt:
          hosts:
            ictad22h02:
            ictad22h01:
----


==== Déplacer temporairement un service BeeGFS vers un autre nœud de fichier

De manière générale, si un nœud est en cours de maintenance, il convient d'utiliser [les étapes de basculement et de retour arrière](#le basculement et la restauration) pour déplacer tous les services hors de ce nœud.

Si vous devez déplacer un service individuel vers un autre nœud de fichiers :

[source, console]
----
pcs resource move <SERVICE>-monitor <HOSTNAME>
----

WARNING: Ne spécifiez pas les ressources individuelles ou le groupe de ressources. Spécifiez toujours le nom du moniteur pour le service BeeGFS que vous souhaitez déplacer. Par exemple, pour déplacer le service de gestion BeeGFS vers ictad22h02 exécutez : `pcs resource move mgmt-monitor ictad22h02`. Ce processus peut être répété afin de déplacer un ou plusieurs services hors de leurs nœuds préférés. Vérifiez à l'aide de `pcs status` les services ont été transférés/démarrés sur le nouveau nœud.

Pour déplacer un service BeeGFS vers son nœud préféré, effacez d'abord les contraintes de ressources temporaires (en répétant cette étape comme nécessaire pour plusieurs services) :

[source, yaml]
----
pcs resource clear <SERVICE>-monitor
----
Ensuite, une fois prêt à rapatrier les services sur les nœuds de leur choix :

[source, yaml]
----
pcs resource relocate run
----
Notez que cette commande permet de transférer tous les services qui ne disposent plus de contraintes temporaires en termes de ressources, situés sur les nœuds de leur choix.
