---
sidebar: sidebar 
permalink: custom-architectures-setup-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Configurez un nœud de contrôle Ansible pour déployer et gérer le système de fichiers. 
---
= Configurez le nœud de contrôle Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Configurez un nœud de contrôle Ansible pour déployer et gérer le système de fichiers.



== Présentation

Un nœud de contrôle Ansible est une machine Linux physique ou virtuelle utilisée pour gérer le cluster. Il doit répondre aux exigences suivantes :

* Découvrez le link:beegfs-technology-requirements.html#ansible-control-node-requirements["de formation"^] Pour le rôle BeeGFS HA, y compris les versions installées d'Ansible, Python et tout autre paquet Python supplémentaire.
* Rencontrez l'agent link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#control-node-requirements["Configuration requise pour le nœud de contrôle Ansible"^] y compris les versions de système d'exploitation.
* Accès SSH et HTTPS à tous les nœuds de fichiers et de blocs.


Des étapes d'installation détaillées sont disponibles link:beegfs-deploy-setting-up-an-ansible-control-node.html["ici"^].
