---
sidebar: sidebar 
permalink: administer-clusters-ansible-pcs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, pcs, Ansible 
summary: 'Quand devriez-vous utiliser Ansible par rapport à l"outil de ligne de commande pcs pour gérer le cluster HA ?' 
---
= Quand utiliser Ansible contre l'outil pcs
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quand devriez-vous utiliser Ansible par rapport à l'outil de ligne de commande pcs pour gérer le cluster HA ?

Toutes les tâches de déploiement et de reconfiguration du cluster doivent être effectuées à l'aide d'Ansible à partir d'un nœud de contrôle Ansible externe. Les modifications temporaires de l'état du cluster (par exemple, placement des nœuds en veille ou en dehors) sont généralement effectuées en se connectant à un nœud du cluster (de préférence un nœud qui n'est pas dégradé ou sur le point de subir des opérations de maintenance) et en utilisant l'outil de ligne de commande pcs.

Tout changement de configuration de cluster, y compris les ressources, les contraintes, les propriétés et les services BeeGFS, doit toujours être effectué à l'aide d'Ansible. Maintenir une copie à jour de l'inventaire et du manuel de vente Ansible (idéalement en contrôle source pour suivre les modifications) fait partie de la maintenance du cluster. Si vous devez modifier la configuration, mettez à jour l'inventaire et exécutez à nouveau le PlayBook Ansible qui importe le rôle BeeGFS HA.

Le rôle HA gère le placement du cluster en mode maintenance, puis les modifications nécessaires avant de redémarrer BeeGFS ou les services du cluster pour appliquer la nouvelle configuration. Le redémarrage complet de nœud n'est généralement pas nécessaire en dehors du déploiement initial. Toutefois, le redémarrage d'Ansible est généralement considéré comme une procédure « sûre », mais toujours recommandé pendant les fenêtres de maintenance ou hors heures si les services BeeGFS doivent redémarrer. Ces redémarrages ne doivent généralement pas provoquer d'erreurs d'application, mais peuvent nuire aux performances (que certaines applications peuvent traiter mieux que d'autres).

Le réexécution Ansible est également une option pour rétablir l'état optimal de l'ensemble du cluster. Dans certains cas, il peut récupérer l'état du cluster plus facilement qu'avec les pièces. Notamment en cas d'urgence où le cluster est hors service, une fois que tous les nœuds sont sauvegardées, Ansible peut récupérer le cluster plus rapidement et de façon plus fiable que toute tentative d'utilisation de pcs.
