---
sidebar: sidebar 
permalink: administer/clusters-stop-start-cluster.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, stop, start 
summary: Arrêt et démarrage du cluster HA avec élégance. 
---
= Arrêtez et démarrez le cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Arrêt et démarrage du cluster HA avec élégance.



== Présentation

Cette section décrit comment arrêter et redémarrer le cluster BeeGFS. Par exemple, la maintenance électrique ou la migration d'un data Center à l'autre ou d'un rack peut être nécessaire.



== Étapes

Si, pour une raison quelconque, vous devez arrêter tout le cluster BeeGFS et arrêter tous les services exécutent :

[source, console]
----
pcs cluster stop --all
----
Il est également possible d'arrêter le cluster sur des nœuds individuels (qui basculeront automatiquement les services vers un autre nœud), bien qu'il soit d'abord recommandé de mettre le nœud en veille (voir la link:clusters-failover-failback.html["basculement"^] section) :

[source, console]
----
pcs cluster stop <HOSTNAME>
----
Pour démarrer les ressources et les services du cluster sur tous les nœuds, exécutez :

[source, console]
----
pcs cluster start --all
----
Ou démarrer les services sur un nœud spécifique avec :

[source, console]
----
pcs cluster start <HOSTNAME>
----
À ce stade, exécuter `pcs status` Et vérifiez que le cluster et les services BeeGFS démarrent sur tous les nœuds et que les services sont exécutés sur les nœuds que vous attendez.


TIP: Selon la taille du cluster, l'arrêt de l'ensemble du cluster peut prendre des secondes ou des minutes, ou s'afficher comme démarré dans `pcs status`. si `pcs cluster <COMMAND>` se bloque pendant plus de cinq minutes, avant d'exécuter « Ctrl+C » pour annuler la commande, connectez-vous à chaque nœud du cluster et utilisez `pcs status` pour voir si les services de cluster (Corosync/Pacemaker) sont toujours en cours d'exécution sur ce nœud. A partir de n'importe quel nœud où le cluster est toujours actif, vous pouvez vérifier les ressources qui bloquent le cluster. Résoudre manuellement le problème et la commande doit être terminée ou réexécutée pour arrêter les services restants.
