---
sidebar: sidebar 
permalink: administer/clusters-upgrade-beegfs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, update, upgrade 
summary: Utilisez Ansible pour mettre à jour BeeGFS et le cluster HA. 
---
= Mise à niveau des services BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilisez Ansible pour mettre à jour la version de BeeGFS exécutée sur votre cluster HA.



== Présentation

BeeGFS applique un `major.minor.patch` schéma de gestion des versions. Des rôles Ansible haute disponibilité BeeGFS sont fournis pour chaque `major.minor` version prise en charge (par exemple, `beegfs_ha_7_2` et `beegfs_ha_7_3`). Chaque rôle HA est épinglé à la dernière version de correctif BeeGFS disponible au moment de la publication de la collection Ansible.

Ansible doit être utilisé pour toutes les mises à niveau de BeeGFS, y compris le passage entre les versions majeure, mineure et corrective de BeeGFS. Pour mettre à jour BeeGFS, vous devrez d'abord mettre à jour la collection Ansible BeeGFS, ce qui intégrera également les derniers correctifs et améliorations de l'automatisation du déploiement/gestion et du cluster HA sous-jacent. Même après la mise à jour vers la dernière version de la collection, BeeGFS ne sera pas mis à niveau tant que  `ansible-playbook` n'aura pas été exécuté avec l' `-e "beegfs_ha_force_upgrade=true"` activé. Pour plus de détails sur chaque mise à niveau, consultez la link:https://doc.beegfs.io/latest/advanced_topics/upgrade.html["Documentation de mise à niveau BeeGFS"^] pour votre version actuelle.


NOTE: Si vous effectuez une mise à niveau vers BeeGFS 8, consultez plutôt la link:clusters-upgrade-beegfs-v8.html["Mise à niveau vers BeeGFS 8"]procédure.



== Chemins de mise à niveau testés

Les voies de mise à niveau suivantes ont été testées et vérifiées :

[cols="1,1,1,5"]
|===
| Version d'origine | Mettre à niveau la version | Multirail | Détails 


| 7.2.6 | 7.3.2 | Oui. | Mise à niveau de la collection beegfs de v3.0.1 à v3.1.0, multirail ajouté 


| 7.2.6 | 7.2.8 | Non | Mise à niveau de la collection beegfs de v3.0.1 à v3.1.0 


| 7.2.8 | 7.3.1 | Oui. | Mise à niveau avec beegfs collection v3.1.0, multirail ajouté 


| 7.3.1 | 7.3.2 | Oui. | Mise à niveau avec beegfs collection v3.1.0 


| 7.3.2 | 7.4.1 | Oui. | Mise à niveau avec beegfs collection v3.2.0 


| 7.4.1 | 7.4.2 | Oui. | Mise à niveau avec beegfs collection v3.2.0 


| 7.4.2 | 7.4.6 | Oui. | Mise à niveau avec beegfs collection v3.2.0 


| 7.4.6 | 8,0 | Oui. | Mettez à niveau en suivant les instructions dans la link:clusters-upgrade-beegfs-v8.html["Mise à niveau vers BeeGFS 8"] procédure. 


| 7.4.6 | 8,1 | Oui. | Mettez à niveau en suivant les instructions dans la link:clusters-upgrade-beegfs-v8.html["Mise à niveau vers BeeGFS 8"] procédure. 


| 7.4.6 | 8,2 | Oui. | Mettez à niveau en suivant les instructions dans la link:clusters-upgrade-beegfs-v8.html["Mise à niveau vers BeeGFS 8"] procédure. 
|===


== Étapes de mise à niveau BeeGFS

Les sections suivantes expliquent comment mettre à jour la collection BeeGFS Ansible et BeeGFS. Portez une attention particulière à toute étape(s) supplémentaire(s) pour la mise à jour de BeeGFS version majeure ou mineure.



=== Étape 1 : mise à niveau de la collection BeeGFS

Pour les mises à niveau de collecte avec accès à link:https://galaxy.ansible.com/netapp_eseries/beegfs["Galaxy Ansible"^], exécutez la commande suivante :

[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs --upgrade
----
Pour les mises à niveau hors ligne de la collection, téléchargez la collection à partir de link:https://galaxy.ansible.com/netapp_eseries/beegfs["Galaxy Ansible"^] en cliquant sur le bouton souhaité `Install Version`` puis `Download tarball`. Transférez le tarball sur votre nœud de contrôle Ansible, puis exécutez la commande suivante.

[source, console]
----
ansible-galaxy collection install netapp_eseries-beegfs-<VERSION>.tar.gz --upgrade
----
Voir link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html["Installation de Collections"^] pour en savoir plus.



=== Étape 2 : mise à jour de l'inventaire Ansible

Apportez toutes les mises à jour requises ou souhaitées aux fichiers d'inventaire Ansible de votre cluster. Voir la section <<Notes de mise à niveau de la version>> ci-dessous pour plus de détails sur vos exigences spécifiques de mise à niveau. Voir la section link:../custom/architectures-inventory-overview.html["Présentation d'Ansible Inventory"^] pour des informations générales sur la configuration de votre inventaire BeeGFS HA.



=== Étape 3 : mise à jour du PlayBook Ansible (uniquement en cas de mise à jour des versions principales ou secondaires)

Si vous passez d'une version majeure à une version mineure, dans le `playbook.yml` fichier utilisé pour déployer et gérer le cluster, mettez à jour le nom du `beegfs_ha_<VERSION>` rôle pour refléter la version souhaitée. Par exemple, si vous souhaitez déployer BeeGFS 7.4 `beegfs_ha_7_4`:

[source, yaml]
----
- hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - netapp_eseries.beegfs
  tasks:
    - name: Ensure BeeGFS HA cluster is setup.
      ansible.builtin.import_role:  # import_role is required for tag availability.
        name: beegfs_ha_7_4
----
Pour plus de détails sur le contenu de ce fichier PlayBooklink:../custom/architectures-deploy-ha-cluster.html["Déployez le cluster BeeGFS HA"^], reportez-vous à la section.



=== Étape 4 : exécutez la mise à niveau BeeGFS

Pour appliquer la mise à jour BeeGFS :

[source, console]
----
ansible-playbook -i inventory.yml beegfs_ha_playbook.yml -e "beegfs_ha_force_upgrade=true" --tags beegfs_ha
----
En coulisse, le rôle haute disponibilité BeeGFS gère :

* Assurez-vous que le cluster est dans un état optimal avec chaque service BeeGFS situé sur son nœud préféré.
* Mettre le cluster en mode maintenance.
* Mettre à jour les composants du cluster haute disponibilité (le cas échéant)
* Mettez à niveau chaque nœud de fichiers un par un en procédant comme suit :
+
** Mettez le système en veille et basculez ses services vers le nœud secondaire.
** Mise à jour des packs BeeGFS.
** Proposer de nouveaux services.


* Déplacez le cluster hors du mode maintenance.




== Notes de mise à niveau de la version



=== Mise à jour de BeeGFS version 7.2.6 ou 7.3.0



==== Modifications de l'authentification basée sur la connexion

BeeGFS version 7.3.2 et ultérieures nécessitent que l’authentification basée sur la connexion soit configurée. Les services ne démarreront pas sans l’une des options suivantes :

* Spécifier un `connAuthFile`, ou
* Paramétrage `connDisableAuthentication=true` dans le fichier de configuration du service.


Il est fortement recommandé d'activer l'authentification basée sur la connexion pour des raisons de sécurité. Voir link:https://doc.beegfs.io/7.3.2/advanced_topics/authentication.html#connectionbasedauth["Authentification basée sur la connexion BeeGFS"^] pour plus d'informations.

Les `beegfs_ha*` rôles génèrent et distribuent automatiquement le fichier d'authentification à :

* Tous les nœuds de fichiers du cluster
* Le nœud de contrôle Ansible à `<playbook_directory>/files/beegfs/<beegfs_mgmt_ip_address>_connAuthFile`


Le  `beegfs_client` rôle détectera et appliquera automatiquement ce fichier aux clients lorsqu'il sera présent.


WARNING: Si vous n'avez pas utilisé le  `beegfs_client` rôle pour configurer les clients, vous devez distribuer manuellement le fichier d'authentification à chaque client et configurer le paramètre  `connAuthFile` dans le fichier  `beegfs-client.conf`. Lors d'une mise à niveau depuis une version de BeeGFS sans authentification basée sur la connexion, les clients perdront l'accès sauf si vous désactivez l'authentification basée sur la connexion pendant la mise à niveau en définissant  `beegfs_ha_conn_auth_enabled: false` dans  `group_vars/ha_cluster.yml` (non recommandé).

Pour plus de détails et d'options de configuration alternatives, consultez l'étape de configuration de l'authentification de connexion dans la section link:../custom/architectures-inventory-common-file-node-configuration.html["Spécifiez la configuration de nœud de fichier commun"^].
