---
sidebar: sidebar 
permalink: custom/architectures-deploy-playbook-overview.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 'Déploiement et gestion de clusters BeeGFS HA à l"aide d"Ansible.' 
---
= Présentation du PlayBook Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Déploiement et gestion de clusters BeeGFS HA à l'aide d'Ansible.



== Présentation

Les sections précédentes ont parcouru les étapes nécessaires à la création d'un inventaire Ansible représentant un cluster BeeGFS HA. Cette section présente l'automatisation Ansible développée par NetApp pour déployer et gérer le cluster.



== Ansible : principaux concepts

Avant de commencer, il est utile de connaître quelques concepts clés Ansible :

* Les tâches à exécuter avec un inventaire Ansible sont définies dans ce qu'on appelle *PlayBook*.
+
** La plupart des tâches dans Ansible sont conçues pour être *idempotent*, ce qui signifie qu'elles peuvent être exécutées plusieurs fois pour vérifier que la configuration/l'état désiré est toujours appliqué sans briser les choses ou faire des mises à jour inutiles.


* La plus petite unité d'exécution dans Ansible est un *module*.
+
** Les playbooks classiques utilisent plusieurs modules.
+
*** Exemples : télécharger un package, mettre à jour un fichier de configuration, démarrer/activer un service.


** NetApp distribue des modules pour automatiser les systèmes NetApp E-Series.


* Une automatisation complexe est mieux prédéfinie.
+
** Il s'agit essentiellement d'un format standard permettant de distribuer un PlayBook réutilisable.
** NetApp distribue des rôles pour les hôtes Linux et les systèmes de fichiers BeeGFS.






== BeeGFS HA role pour Ansible : concepts clés

Tout l'automatisation nécessaire au déploiement et à la gestion de chaque version de BeeGFS sur NetApp est un rôle Ansible et distribué dans le link:https://galaxy.ansible.com/netapp_eseries/beegfs["NetApp E-Series Ansible Collection pour BeeGFS"^]:

* Ce rôle peut être considéré comme quelque part entre un *installateur* et un * moderne *déploiement/gestion* moteur pour BeeGFS.
+
** Applique une infrastructure moderne en tant que pratiques du code et philosophie pour simplifier la gestion de l'infrastructure de stockage à toute échelle.
** De la même façon que link:https://github.com/kubernetes-sigs/kubespray["Priez"^]le projet permet aux utilisateurs de déployer/gérer une distribution Kubernetes complète pour une infrastructure de calcul scale-out.


* Il s'agit du format *Software-defined* que NetApp utilise pour créer, distribuer et gérer les solutions BeeGFS sur NetApp.
+
** S'efforcer de créer une expérience de type appareil sans avoir à distribuer une distribution Linux entière ou une image de grande taille.
** Inclut des agents de ressources de cluster conformes à la norme OCF (Open Cluster Framework) de NetApp pour les cibles BeeGFS, les adresses IP et la surveillance personnalisés qui fournissent une intégration Pacemaker/BeeGFS intelligente.


* Le rôle ne se limite pas au déploiement de l'« automatisation ». Il est destiné à gérer l'ensemble du cycle de vie du système de fichiers, notamment :
+
** Modification et mise à jour de la configuration au niveau du service ou du cluster
** Automatisation de la réparation et de la restauration de clusters après une résolution des problèmes matériels
** Simplification du réglage des performances avec des valeurs par défaut définies sur la base de tests approfondis réalisés avec BeeGFS et les volumes NetApp.
** Vérification et correction de la dérive de configuration.




NetApp fournit également un rôle Ansible pour link:https://github.com/netappeseries/beegfs/tree/master/roles/beegfs_client["Clients BeeGFS"^], Qui peut éventuellement être utilisé pour installer des systèmes de fichiers BeeGFS et monter des nœuds de calcul/GPU/connexion.
