---
sidebar: sidebar 
permalink: custom/architectures-setup-nodes.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 'Étapes manuelles nécessaires pour configurer les nœuds de blocs et de fichiers avant d"exécuter Ansible.' 
---
= Configurez les nœuds de fichier et de bloc
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Étapes manuelles nécessaires pour configurer les nœuds de blocs et de fichiers avant d'exécuter Ansible.



== Nœuds de fichiers



=== Configuration du contrôleur BMC (Baseboard Management Controller)

Un contrôleur de gestion de la carte mère (BMC), parfois appelé processeur de service, est le nom générique de la fonctionnalité de gestion hors bande intégrée dans diverses plates-formes de serveurs qui fournissent un accès à distance même si le système d'exploitation n'est pas installé ou accessible. Les fournisseurs vendent généralement cette fonctionnalité avec leur propre marque. Par exemple, sur le Lenovo SR665, le contrôleur BMC est appelé XCC (Lenovo XClarity Controller).

Suivez la documentation du fournisseur du serveur pour activer toutes les licences nécessaires pour accéder à cette fonctionnalité et vérifier que le contrôleur BMC est connecté au réseau et configuré de manière appropriée pour l'accès à distance.


NOTE: Si vous souhaitez utiliser Redfish pour l'escrime basé sur BMC, assurez-vous que Redfish est activé et que l'interface BMC est accessible à partir du système d'exploitation installé sur le nœud de fichiers. Une configuration spéciale peut être nécessaire sur le commutateur réseau si le contrôleur BMC et le système d'exploitation partagent la même interface réseau physique.



=== Réglage des paramètres système

À l'aide de l'interface de configuration du système (BIOS/UEFI), assurez-vous que les paramètres sont définis pour optimiser les performances. Les paramètres exacts et les valeurs optimales varient en fonction du modèle de serveur utilisé. Des conseils sont fournis pour link:../second-gen/beegfs-deploy-file-node-tuning.html["modèles de nœud de fichier vérifiés"^], sinon reportez-vous à la documentation du fournisseur du serveur et aux meilleures pratiques en fonction de votre modèle.



=== Installer un système d'exploitation

Installez un système d'exploitation pris en charge en fonction de la configuration requise pour link:../second-gen/beegfs-technology-requirements.html#file-node-requirements["ici"^]le nœud de fichiers indiquée . Reportez-vous aux étapes supplémentaires ci-dessous en fonction de votre distribution Linux.



==== Red Hat

Utilisez RedHat Subscription Manager pour enregistrer et abonner le système afin de permettre l'installation des packages requis dans les référentiels Red Hat officiels et de limiter les mises à jour vers la version prise en charge de Red Hat : `subscription-manager release --set=<MAJOR_VERSION>.<MINOR_VERSION>`. Pour obtenir des instructions, reportez-vous à la section https://access.redhat.com/solutions/253273["Comment enregistrer et souscrire un système RHEL"^] et  https://access.redhat.com/solutions/2761031["Comment limiter les mises à jour"^].

Activez le référentiel Red Hat contenant les packages requis pour la haute disponibilité :

....
subscription-manager repo-override --repo=rhel-9-for-x86_64-highavailability-rpms --add=enabled:1
....


=== Configurer le réseau de gestion

Configurez toutes les interfaces réseau nécessaires pour permettre la gestion intrabande du système d'exploitation. Les étapes exactes dépendent de la distribution et de la version spécifiques de Linux utilisées.


NOTE: Assurez-vous que SSH est activé et que toutes les interfaces de gestion sont accessibles depuis le nœud de contrôle Ansible.



=== Mettre à jour le micrologiciel HCA et HBA

Assurez-vous que tous les HBA et les HCA exécutent les versions de micrologiciel prises en charge répertoriées sur le link:https://imt.netapp.com/matrix/["Matrice d'interopérabilité NetApp"^] et mettez à niveau si nécessaire. Des recommandations supplémentaires pour les adaptateurs NVIDIA ConnectX sont disponibles link:../second-gen/beegfs-technology-requirements.html#file-node-requirements["ici"^].



== Nœuds de blocs

Suivez les étapes à link:https://docs.netapp.com/us-en/e-series/getting-started/getup-run-concept.html["Mise en service de la gamme E-Series"^] pour configurer le port de gestion sur chaque contrôleur de nœud de bloc et définir éventuellement le nom de la matrice de stockage pour chaque système.


NOTE: Aucune configuration supplémentaire ne s'applique à garantir que tous les nœuds de bloc sont accessibles depuis le nœud de contrôle Ansible. La configuration système restante sera appliquée/gérée à l'aide d'Ansible.
