---
sidebar: sidebar 
permalink: custom-architectures-overview.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 'La solution BeeGFS sur NetApp associe le système de fichiers parallèle BeeGFS aux systèmes de stockage NetApp E-Series, pour obtenir une infrastructure fiable, évolutive et économique qui s"adapte aux besoins des workloads les plus exigeants.' 
---
= Présentation et configuration requise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilisez tous les systèmes de stockage NetApp E/EF-Series comme nœuds de bloc BeeGFS et serveurs x86 comme nœuds de fichiers BeeGFS lors du déploiement de clusters haute disponibilité BeeGFS à l'aide d'Ansible.


TIP: Les définitions de la terminologie utilisée dans cette section se trouvent sur le link:beegfs-terms.html["termes et concepts"] page.



== Introduction

Pendant link:beegfs-solution-overview.html["Architectures vérifiées NetApp"] fournissez des configurations de référence prédéfinies et des conseils sur le dimensionnement, certains clients et partenaires peuvent préférer concevoir des architectures personnalisées mieux adaptées à des exigences spécifiques ou à des préférences matérielles. L'un des principaux avantages de BeeGFS sur NetApp est la possibilité de déployer des clusters HA à disque partagé BeeGFS à l'aide d'Ansible, en simplifiant la gestion du cluster et en améliorant la fiabilité grâce aux composants HA de NetApp. Le déploiement d'architectures BeeGFS sur NetApp est toujours réalisé à l'aide d'Ansible, tout en conservant une approche de type appliance sur un éventail flexible de matériel.

Cette section présente les étapes générales requises pour déployer des systèmes de fichiers BeeGFS sur du matériel NetApp et pour utiliser Ansible afin de configurer les systèmes de fichiers BeeGFS. Pour plus de détails sur les pratiques exemplaires entourant la conception de systèmes de fichiers BeeGFS et des exemples optimisés, veuillez consulter le link:beegfs-solution-overview.html["Architectures vérifiées NetApp"] section.



== Présentation du déploiement

Le déploiement d'un système de fichiers BeeGFS implique généralement les étapes suivantes :

* Configuration initiale :
+
** Installer/raccorder le matériel de fixation.
** Configurez les nœuds de fichiers et de blocs.
** Configurez un nœud de contrôle Ansible.


* Définissez le système de fichiers BeeGFS comme un inventaire Ansible.
* Exécutez Ansible sur des nœuds de fichiers et de blocs pour déployer BeeGFS.
+
** Vous pouvez également configurer des clients et monter BeeGFS.




Les sections suivantes couvriront ces étapes plus en détail.

[NOTE]
====
Ansible gère toutes les tâches de provisionnement et de configuration des logiciels, y compris :

* Création/mappage de volumes sur des nœuds de blocs.
* Formatage/réglage des volumes sur les nœuds de fichiers.
* Installation/configuration du logiciel sur les nœuds de fichiers.
* Création du cluster HA et configuration des ressources BeeGFS et des services de système de fichiers.


====


== De formation

La prise en charge de BeeGFS dans Ansible est activée link:https://galaxy.ansible.com/netapp_eseries/beegfs["Galaxy Ansible"] Ensemble de rôles et de modules qui automatisent le déploiement et la gestion de bout en bout des clusters BeeGFS HA.

BeeGFS est également versionné suivant un schéma de gestion des versions <major>.<minor>.<patch> et la collection conserve les rôles pour chaque version <major>.<minor> prise en charge de BeeGFS, par exemple BeeGFS 7.2 ou BeeGFS 7.3. À mesure que les mises à jour de la collection sont publiées, la version patch dans chaque rôle sera mise à jour pour pointer à la dernière version BeeGFS disponible pour cette branche de publication (exemple : 7.2.8). Chaque version de la collection est également testée et prise en charge avec des distributions et versions spécifiques de Linux, actuellement Red Hat pour les nœuds de fichiers, et RedHat et Ubuntu pour les clients. L'exécution d'autres distributions n'est pas prise en charge et l'exécution d'autres versions (en particulier d'autres versions majeures) n'est pas recommandée.



=== Nœud de contrôle Ansible

Ce nœud contiendra l'inventaire et les manuels de vente utilisés pour gérer BeeGFS. Elle requiert :

* Ansible 6.x (noyau ansible 2.13)
* Python 3.6 (ou version ultérieure)
* Paquets Python (pip) : ipadr et netaddr


Il est également recommandé d'installer SSH sans mot de passe depuis le nœud de contrôle vers tous les nœuds de fichiers et clients BeeGFS.



=== Nœuds de fichiers BeeGFS

Les nœuds de fichiers doivent exécuter RedHat 9.3 et avoir accès au référentiel HA contenant les packages requis (stimulateur, corosync, clôture-agents-tous, agents-ressources). Par exemple, la commande suivante peut être exécutée pour activer le référentiel approprié sur RedHat 9 :

[source, bash]
----
subscription-manager repo-override repo=rhel-9-for-x86_64-highavailability-rpms --add=enabled:1
----


=== Nœuds clients BeeGFS

Un rôle de client BeeGFS Ansible est disponible pour installer le paquet client BeeGFS et gérer le(s) BeeGFS mount(s). Ce rôle a été testé avec RedHat 8.4 et Ubuntu 22.04.

Si vous n'utilisez pas Ansible pour configurer le client BeeGFS et monter BeeGFS, tout link:https://doc.beegfs.io/latest/release_notes.html#supported-linux-distributions-and-kernels["BeeGFS prend en charge la distribution et le noyau Linux"] peut être utilisé.
