---
sidebar: sidebar 
permalink: custom-architectures-deploy-verify.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Vérifiez le déploiement du système de fichiers avant de mettre le système en production. 
---
= Vérifier le déploiement BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vérifiez le déploiement du système de fichiers avant de mettre le système en production.



== Présentation

Avant de placer le système de fichiers BeeGFS en production, effectuez quelques vérifications.



=== Étapes

. Connectez-vous à n'importe quel client et exécutez les opérations suivantes pour vous assurer que tous les nœuds attendus sont présents/accessibles, et qu'il n'y a pas d'incohérences ou d'autres problèmes signalés :
+
[source, bash]
----
beegfs-fsck --checkfs
----
. Arrêtez l'ensemble du cluster, puis redémarrez-le. Depuis n'importe quel nœud de fichiers, exécutez ce qui suit :
+
[source, bash]
----
pcs cluster stop --all # Stop the cluster on all file nodes.
pcs cluster start --all  # Start the cluster on all file nodes.
pcs status # Verify all nodes and services are started and no failures are reported (the command may need to be reran a few times to allow time for all services to start).
----
. Placez chaque nœud en veille et vérifiez que les services BeeGFS peuvent basculer vers un ou plusieurs nœuds secondaires. Pour ce faire, connectez-vous à l'un des nœuds de fichiers et exécutez les opérations suivantes :
+
[source, bash]
----
pcs status # Verify the cluster is healthy at the start.
pcs node standby <FILE NODE HOSTNAME> # Place the node under test in standby.
pcs status # Verify services are started on a secondary node and no failures are reported.
pcs node unstandby <FILE NODE HOSTNAME> # Take the node under test out of standby.
pcs status # Verify the file node is back online and no failures are reported.
pcs resource relocate run # Move all services back to their preferred nodes.
pcs status # Verify services have moved back to the preferred node.
----
. Utilisez des outils d'évaluation des performances tels que IOR et MDTest pour vérifier que les performances du système de fichiers répondent aux attentes. Des exemples de tests et de paramètres communs utilisés avec BeeGFS se trouvent dans le link:/beegfs-design-solution-verification.html["Vérification de la conception"^] Section BeeGFS sur l'architecture vérifiée NetApp.


Des tests supplémentaires doivent être effectués en fonction des critères d'acceptation définis pour un site/une installation spécifique.
