---
sidebar: sidebar 
permalink: whats-included.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: 'Ce site inclut des informations spécifiques à la solution NetApp Verified Architecture (NVA) pour BeeGFS sur NetApp.' 
---
= Ce qui est inclus dans ce site
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Ce site fournit des informations spécifiques à la deuxième génération de l'architecture vérifiée NetApp (NVA) pour BeeGFS sur NetApp.

Ce site comprend les informations suivantes :

* Considérations relatives à la conception de l'architecture utilisées pour déterminer l'équipement, le câblage et les configurations spécifiques nécessaires pour prendre en charge l'architecture. Pour plus d'informations, voir link:beegfs-design-overview.html["Présentation du design"].
* Instructions de déploiement à l'aide de serveurs de fichiers BeeGFS (nœuds de fichiers) validés reliés à des systèmes de stockage bloc (nœuds de blocs). Pour plus d'informations, voir link:beegfs-deploy-overview.html["Présentation du déploiement"].


Ce site propose _NOT_ des informations de conception et de déploiement pour la première génération de la solution. Pour obtenir le contenu complet de la génération précédente, reportez-vous à la section link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["NetApp EF-Series ai avec NVIDIA DGX A100 et BeeGFS"^].
