---
sidebar: sidebar 
permalink: get-started/whats-included.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Ce site explique comment déployer et gérer BeeGFS sur NetApp. 
---
= Ce qui est inclus dans ce site
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Ce site explique comment déployer et gérer BeeGFS sur NetApp à la fois sur les architectures vérifiées NetApp (NVA) et sur les architectures personnalisées. Les designs NVA sont minutieusement testés et fournissent aux clients des configurations de référence et des conseils de dimensionnement afin de réduire les risques de déploiement et d'accélérer la mise sur le marché. NetApp prend également en charge les architectures BeeGFS sous forme de matériel NetApp, ce qui offre à vos clients et partenaires la flexibilité nécessaire à la conception de systèmes de fichiers pour répondre à un large éventail d'exigences. Ces deux approches exploitent Ansible pour le déploiement, et offrent une approche de type appliance pour gérer BeeGFS à n'importe quelle échelle sur un éventail flexible de matériel.
